import {LITERATURE} from './literature.js';
import {IDEAS,BOOKS,QUOTES,CONCERNS,RECOMMENDATIONS,REASONS} from './content.js';
import {normalize,prioritize,reorder,pickIdea,dailyIndex} from './logic.js';
const KEY='manmanlai.v1',IDEA_KEY='manmanlai.last-idea';
const app=document.querySelector('#app'),dialog=document.querySelector('#dialog');
const esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const uid=()=>crypto.randomUUID?.()||`${Date.now()}-${Math.random().toString(36).slice(2)}`;
const emptyData=()=>({wishes:[],entries:[],todos:[]});
let data=emptyData(),storageOK=true,page='today',selectedMood='',moodDraft='',todoDraft='',activeIdea=null,reflection='',quizConcern='',quizStyle='',lastTrigger=null;
try{const raw=localStorage.getItem(KEY);if(raw)data=normalize(JSON.parse(raw));}catch{storageOK=false;}
let suggestion,undoTask=null;
function nextSuggestion(){let previous=suggestion?.id;try{previous=previous||localStorage.getItem(IDEA_KEY);}catch{}suggestion=pickIdea(IDEAS,previous);try{localStorage.setItem(IDEA_KEY,suggestion.id);}catch{}}
nextSuggestion();
function save(next){if(!storageOK){toast('暂时无法保存，请检查浏览器的存储设置。');return false;}try{localStorage.setItem(KEY,JSON.stringify(next));data=next;return true;}catch{storageOK=false;toast('保存没有成功，请保留输入的文字，稍后再试。');return false;}}
function toast(message){const el=document.querySelector('#toast');el.textContent=message;el.classList.add('visible');clearTimeout(toast.timer);toast.timer=setTimeout(()=>el.classList.remove('visible'),3500);}
const icons={arrow:'<path d="M5 12h14m-5-5 5 5-5 5"/>',plus:'<path d="M12 5v14M5 12h14"/>',close:'<path d="m6 6 12 12M6 18 18 6"/>',check:'<path d="m5 12 4 4L19 6"/>',heart:'<path d="M20 5a5 5 0 0 0-8 1 5 5 0 0 0-8-1c-5 5 3 11 8 15 5-4 13-10 8-15Z"/>',book:'<path d="M12 5v15M3 4c4-1 6 0 9 2 3-2 5-3 9-2v15c-4-1-6 0-9 2-3-2-5-3-9-2Z"/>',refresh:'<path d="M20 8a8 8 0 1 0 0 8M20 3v5h-5"/>',trash:'<path d="M3 6h18M9 6V3h6v3M5 6l1 15h12l1-15M10 10v7m4-7v7"/>',up:'<path d="m6 14 6-6 6 6"/>',down:'<path d="m6 10 6 6 6-6"/>'};
function icon(name){return `<svg viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="1.5" stroke-linecap="round" stroke-linejoin="round" aria-hidden="true">${icons[name]||icons.heart}</svg>`;}
const moodNames=['有点低落','有些疲惫','说不清楚','还算平静','有点开心'];
function face(i){const mouths=['M14 27q6-7 12 0','M15 26h10','M16 26q4-2 8 0','M15 24q5 5 10 0','M13 23q7 10 14 0'];return `<svg viewBox="0 0 40 40" fill="none" stroke="currentColor" stroke-width="1.4" stroke-linecap="round" aria-hidden="true"><circle cx="20" cy="20" r="17"/><path d="M14 15v2m12-2v2"/><path d="${mouths[i]}"/></svg>`;}
function dateLabel(at){return new Intl.DateTimeFormat('zh-CN',{month:'long',day:'numeric'}).format(new Date(at));}
function dayKey(at){const d=new Date(at);return `${d.getFullYear()}-${d.getMonth()+1}-${d.getDate()}`;}
function findIdea(id){return [...IDEAS,...data.wishes,...data.todos].find(x=>x.id===id);}
function dailyQuote(){return QUOTES[dailyIndex(new Date(),QUOTES.length)];}
function bookQuote(b){return QUOTES.find(q=>q.bookId===b.id);}
function quoteBlock(q,compact=false){const b=BOOKS.find(x=>x.id===q.bookId);return `<div class="${compact?'daily-quote':'book-quote'}"><span class="eyebrow">${compact?'今日的一句':'从书里，借一点光'}</span><blockquote>“${esc(q.text)}”</blockquote><button class="source-link" data-action="quote" data-book="${b.id}" data-quote="${QUOTES.indexOf(q)}">《${b.title}》 · ${b.author}<span>本站译文 · 查看出处 ↗</span></button></div>`;}
function render(){const oldPage=app.dataset.page,scroll=window.scrollY,focused=document.activeElement;
const focusKey=focused&&app.contains(focused)?{id:focused.id,action:focused.dataset.action,item:focused.dataset.id}:null;
const opened=[...app.querySelectorAll('details[open]')].map(x=>x.className);
page=['today','todo','reading','wishes','history'].includes(location.hash.slice(1))?location.hash.slice(1):'today';document.querySelectorAll('[data-page]').forEach(a=>{const active=a.dataset.page===page||(a.dataset.page==='wishes'&&page==='history');if(active)a.setAttribute('aria-current','page');else a.removeAttribute('aria-current');});app.className=`page-${page}`;app.innerHTML=(!storageOK?'<p class="storage-warning" role="alert">暂时无法读写本地记录，原有内容不会被覆盖。请检查浏览器存储设置。</p>':'')+({today,todo:todoPage,reading:readingPage,wishes:wishesPage,history:historyPage}[page])();app.dataset.page=page;
if(oldPage===page){app.querySelectorAll('details').forEach(x=>{x.open=opened.includes(x.className);});if(focusKey){const target=focusKey.id?document.getElementById(focusKey.id):[...app.querySelectorAll('[data-action]')].find(x=>x.dataset.action===focusKey.action&&x.dataset.id===focusKey.item);(target||app.querySelector('#task-input'))?.focus({preventScroll:true});}window.scrollTo({top:scroll,behavior:'instant'});}
else{animate(app);if(oldPage){const heading=app.querySelector('h1');heading?.setAttribute('tabindex','-1');heading?.focus({preventScroll:true});}}
}
function animate(el){if(!matchMedia('(prefers-reduced-motion: reduce)').matches)el?.animate([{opacity:.3,transform:'translateY(5px)'},{opacity:1,transform:'translateY(0)'}],{duration:180,easing:'ease-out'});}
function notePreview(n,label='文学里的回声'){return `<div class="daily-quote literary-note"><span class="eyebrow">${label}</span><p class="literary-line">${esc(n.title)}</p><button class="source-link" data-action="literature" data-id="${n.id}">${n.author} · 《${n.work}》<span>本站阅读札记 · 展开读一点 ${icon('arrow')}</span></button></div>`;}
function literatureDialog(n){openDialog(`<p class="eyebrow">${n.author} · 《${n.work}》</p><h2 id="dialog-title">${n.title}</h2><p class="muted">${n.context}</p><p class="note-reflection">${n.reflection}</p><p class="translation-label">本站阅读理解与延伸 · 非作者原话</p><a class="source-external" href="${n.source}" target="_blank" rel="noopener noreferrer">${n.label} ↗</a><div class="dialog-actions"><button class="secondary" data-action="${n.kind}">${n.action} ${icon('arrow')}</button></div>`);}

function today(){const hour=new Date().getHours(),greeting=hour<11?'早上好':hour<14?'中午好':hour<18?'下午好':'晚上好';const saved=data.wishes.some(w=>w.sourceId===suggestion.id);return `<section class="home-intro"><div><p class="eyebrow">${dateLabel(new Date())} · 你不是一个人</p><h1>${greeting}，慢慢来。</h1></div><button class="quiet-button mood-entry" data-action="open-mood">${face(3)} 记一笔心情</button></section><div class="home-spread"><section class="single-idea" aria-labelledby="idea-title"><div class="idea-copy"><p class="eyebrow">今天，不妨试试</p><h2 id="idea-title">${esc(suggestion.title)}</h2><p class="idea-description">${esc(suggestion.desc)}</p><div class="idea-actions"><button class="primary" data-action="start" data-id="${suggestion.id}">就做这件事 ${icon('arrow')}</button><button class="quiet-button" data-action="shuffle">${icon('refresh')} 换一个</button><button class="icon-button" data-action="collect" data-id="${suggestion.id}" aria-label="${saved?'已经收藏':'收藏这件小事'}">${icon(saved?'check':'plus')}</button></div></div></section>${notePreview(LITERATURE[dailyIndex(new Date(),LITERATURE.length)],'片刻阅读')}</div>`;}
function openDialog(html){if(!dialog.open)lastTrigger=document.activeElement;dialog.innerHTML=`<button class="icon-button dialog-close" data-action="close" aria-label="关闭">${icon('close')}</button>${html}`;if(!dialog.open)dialog.showModal();const focus=dialog.querySelector('[autofocus]')||dialog.querySelector('#dialog-title');if(focus){if(focus.tagName==='H2')focus.tabIndex=-1;focus.focus({preventScroll:true});}dialog.scrollTop=0;}

function restoreTrigger(){const target=lastTrigger?.isConnected?lastTrigger:[...app.querySelectorAll('[data-action]')].find(x=>x.dataset.action===lastTrigger?.dataset.action&&x.dataset.id===lastTrigger?.dataset.id);(target||app.querySelector('h1'))?.focus({preventScroll:true});}
function closeDialog(){dialog.close();restoreTrigger();}
dialog.addEventListener('cancel',e=>{e.preventDefault();closeDialog();});
function moodDialog(){openDialog(`<p class="eyebrow">留一点时间给自己</p><h2 id="dialog-title">此刻，感觉怎么样？</h2><div class="moods" role="group" aria-label="此刻的心情">${moodNames.map((m,i)=>`<button class="mood" data-action="mood" data-value="${m}" aria-pressed="${selectedMood===m}">${face(i)}<span>${m}</span></button>`).join('')}</div><form id="mood-form"><label class="field"><span>想说的话 <small>选填</small></span><textarea name="note" id="mood-note" maxlength="2000" placeholder="几个字也没关系。">${esc(moodDraft)}</textarea></label><div class="dialog-actions"><button class="primary" type="submit">轻轻记下来</button><button class="text-button" type="button" data-action="close">先不记录</button></div></form>`);}
function addDialog(){openDialog(`<p class="eyebrow">留住一点期待</p><h2 id="dialog-title">我有点想……</h2><form id="wish-form"><label class="field"><span>一个想法</span><input name="title" required maxlength="100" placeholder="比如，做一个温暖的小网站" autofocus></label><label class="field"><span>第一小步 <small>选填</small></span><textarea name="step" maxlength="500" placeholder="写下我希望它带给人的感受。"></textarea></label><div class="dialog-actions"><button class="primary" type="submit">存下这份期待</button></div></form>`);}
function startDialog(idea,edit=false){activeIdea={...idea};if(idea.step&&!edit){doingDialog();return;}openDialog(`<p class="eyebrow">一个小小的开始</p><h2 id="dialog-title">${esc(idea.title)}</h2><form id="start-form"><label class="field"><span>就从这一步开始</span><textarea name="step" maxlength="500" required>${esc(idea.step||'')}</textarea></label><div class="dialog-actions"><button class="primary" type="submit">好，开始吧 ${icon('arrow')}</button><button class="text-button" type="button" data-action="close">以后再说</button></div></form>`);}
function doingDialog(){openDialog(`<p class="eyebrow">按你的节奏来</p><h2 id="dialog-title">这段时间，属于你。</h2><p class="step-display">${esc(activeIdea.step)}</p><p class="muted">不用计时，随时停下来也可以。</p><div class="dialog-actions"><button class="primary" data-action="reflect">我回来了 ${icon('arrow')}</button><button class="text-button" data-action="edit-step">调整这一步</button></div>`);}
function reflectDialog(){reflection='';openDialog(`<p class="eyebrow">欢迎回来</p><h2 id="dialog-title">刚才，感觉怎么样？</h2><form id="reflection-form"><div class="choice-pills" role="group" aria-label="行动之后的感受">${['轻松了一点','有点投入了','还是难受','暂时说不清'].map(v=>`<button type="button" data-action="feeling" data-value="${v}" aria-pressed="false">${v}</button>`).join('')}</div><label class="field"><span>还有什么想说的 <small>选填</small></span><textarea name="note" maxlength="2000" placeholder="还难受也没关系。"></textarea></label><div class="dialog-actions"><button class="primary" type="submit">留下一点足迹</button><button class="text-button" type="button" data-action="close">这次不记录</button></div></form>`);}
const priorityNames={inbox:'先放在这里',now:'先做这一件',next:'接下来',later:'暂时放下'};
function todoRow(t){return `<li class="todo-row ${t.done?'is-done':''}" data-task-id="${esc(t.id)}"><label class="check-target"><input type="checkbox" class="task-check" data-action="toggle-task" data-id="${esc(t.id)}" ${t.done?'checked':''} aria-label="${t.done?'恢复':'完成'}：${esc(t.title)}"></label><div class="task-main"><button class="task-title" data-action="edit-task" data-id="${esc(t.id)}">${esc(t.title)}</button>${t.step&&!t.done?`<p class="task-step">${esc(t.step)}</p>`:''}</div><div class="task-controls">${!t.done&&t.priority!=='now'?`<button class="text-button focus-task" data-action="focus-task" data-id="${esc(t.id)}" aria-label="先做：${esc(t.title)}">先做</button>`:''}<button class="icon-button small" data-action="edit-task" data-id="${esc(t.id)}" aria-label="整理：${esc(t.title)}">···</button></div>${!t.done&&t.priority==='now'?`<button class="text-button task-start" data-action="start" data-id="${esc(t.id)}">${t.step?'开始这一小步':'拆成一小步'} ${icon('arrow')}</button>`:''}</li>`;}
function todoPage(){const completed=data.todos.filter(t=>t.done);return `<section class="page-heading"><p class="eyebrow">给脑子腾一点地方</p><h1>一件一件来。</h1><p class="muted">先记下来，再决定哪件值得先做。</p></section><form id="todo-form" class="capture-form"><label class="sr-only" for="task-input">记下待办事项</label><input id="task-input" name="title" value="${esc(todoDraft)}" maxlength="160" required placeholder="有什么事在脑子里打转？" autocomplete="off"><button class="icon-button" type="submit" aria-label="添加待办">${icon('plus')}</button></form><div class="task-groups">${['now','inbox','next','later'].map(p=>{const tasks=data.todos.filter(t=>!t.done&&t.priority===p);if(p!=='now'&&!tasks.length)return '';return `<section class="task-group ${p==='now'?'focus-group':''}"><h2>${priorityNames[p]}</h2>${tasks.length?`<ul class="todo-list">${tasks.map(todoRow).join('')}</ul>`:`<p class="task-empty">${data.todos.some(t=>!t.done)?'从下面挑一件就好。':'先写下一件事，也可以暂时留空。'}</p>`}</section>`;}).join('')}${completed.length?`<details class="completed"><summary>已经做过的事</summary><ul class="todo-list">${completed.map(todoRow).join('')}</ul></details>`:''}</div><p class="page-note">“先做”只留一件。换一件时，上一件会移到“接下来”。</p>`;}
function editTaskDialog(t){const group=data.todos.filter(x=>!x.done&&x.priority===t.priority),idx=group.findIndex(x=>x.id===t.id);openDialog(`<p class="eyebrow">让事情变得容易开始</p><h2 id="dialog-title">整理这件事</h2><form id="edit-task-form" data-id="${esc(t.id)}"><label class="field"><span>这件事</span><input name="title" maxlength="160" required value="${esc(t.title)}"></label><label class="field"><span>第一小步 <small>选填</small></span><textarea name="step" maxlength="500" placeholder="比如：打开文档，写下一个标题。">${esc(t.step||'')}</textarea></label>${!t.done?`<label class="field"><span>放在哪里</span><select name="priority">${Object.entries(priorityNames).map(([v,l])=>`<option value="${v}" ${t.priority===v?'selected':''}>${l}</option>`).join('')}</select></label>`:''}<div class="dialog-actions"><button class="primary" type="submit">保存</button></div></form><details class="task-more"><summary>更多操作</summary><div class="more-actions">${!t.done?`<button class="text-button" data-action="move-task" data-id="${esc(t.id)}" data-value="-1" ${idx===0?'disabled':''}>上移</button><button class="text-button" data-action="move-task" data-id="${esc(t.id)}" data-value="1" ${idx===group.length-1?'disabled':''}>下移</button>`:''}<button class="text-button danger" data-action="remove-task" data-id="${esc(t.id)}">删除这件事</button></div></details>`);}
function readingPage(){return `<section class="page-heading"><p class="eyebrow">读一点，也很好</p><h1>此刻，哪本书能陪你？</h1><p class="muted">两道小问题，找一个愿意翻开的起点。</p></section><section class="quiz" aria-live="polite">${quizConcern?(quizStyle?resultMarkup():styleQuestion()):concernQuestion()}</section><details class="bookshelf"><summary>也可以自己逛逛书架 <span>6 本书</span></summary><div class="book-list">${BOOKS.map(b=>`<button class="book-item" data-action="book" data-book="${b.id}"><span class="book-color ${b.color}" aria-hidden="true">${icon('book')}</span><span><strong>${b.title}</strong><small>${b.author}</small></span>${icon('arrow')}</button>`).join('')}</div></details><details class="bookshelf literary-shelf"><summary>文学里的回声 <span>4 则札记</span></summary><div class="literary-list">${LITERATURE.map(n=>`<button data-action="literature" data-id="${n.id}"><small>${n.author} · 《${n.work}》</small><span>${n.title}</span>${icon('arrow')}</button>`).join('')}</div></details><p class="page-note">这是阅读偏好问答，不是心理测评。引句为本站译文，附原文与出处。</p>`;}
function concernQuestion(){return `<p class="eyebrow">01 / 02</p><h2 tabindex="-1" id="quiz-heading">最近，什么最牵动你？</h2><div class="quiz-options">${CONCERNS.map(([id,label])=>`<button data-action="concern" data-value="${id}">${label}${icon('arrow')}</button>`).join('')}</div>`;}
function styleQuestion(){return `<div class="quiz-top"><p class="eyebrow">02 / 02</p><button class="text-button" data-action="quiz-back">上一步</button></div><h2 tabindex="-1" id="quiz-heading">你更想怎样读？</h2><div class="quiz-options"><button data-action="reading-style" data-value="practical"><span>换个角度，也试试练习<small>想理解自己，找到一点可以尝试的事。</small></span>${icon('arrow')}</button><button data-action="reading-style" data-value="gentle"><span>轻轻读一点，像有人陪着<small>短句、随笔或故事，不急着找答案。</small></span>${icon('arrow')}</button></div>`;}
function resultMarkup(){const b=BOOKS.find(x=>x.id===RECOMMENDATIONS[quizConcern][quizStyle]);return `<p class="eyebrow">可以先从这一本开始</p><h2 id="quiz-heading" tabindex="-1">《${b.title}》</h2><p class="book-author">${b.author} <span lang="en">· ${b.original}</span></p><p class="recommendation-reason">${REASONS[quizConcern][quizStyle]}</p><div class="result-actions"><button class="primary" data-action="book" data-book="${b.id}">看看这本书 ${icon('book')}</button><button class="text-button" data-action="quiz-reset">重新选一选</button></div>${notePreview(LITERATURE.find(n=>n.tags.includes(quizConcern)),'也许与你此刻有关')}`;}
function bookDialog(b,quoteOnly=false,quote){const q=quote||bookQuote(b);openDialog(`<p class="eyebrow">${quoteOnly?'今日的一句 · 出处':'给自己一个阅读的起点'}</p><h2 id="dialog-title">《${b.title}》</h2><p class="book-author">${b.author}<br><span lang="en">${b.original}</span></p>${quoteOnly?'':`<p class="muted">${b.about}</p>`}<blockquote class="quote-translation">“${esc(q.text)}”</blockquote><p class="translation-label">本站译文 · 非出版译本</p><blockquote class="original-quote" lang="en">${esc(q.original)}</blockquote><a class="source-external" href="${esc(q.source)}" target="_blank" rel="noopener noreferrer">${esc(q.label)} ↗</a>${quoteOnly?'':`<p class="reading-start">${b.start}</p><p class="page-note">可以先在学校或当地的图书馆查找。不同中文版的书名可能略有差异，可按作者或英文名检索。</p><div class="dialog-actions"><button class="secondary" data-action="save-book" data-book="${b.id}">放进我的期待 ${icon('plus')}</button></div>`}`);}
function personalNav(){return `<nav class="personal-tabs" aria-label="我的记录"><a href="#wishes" ${page==='wishes'?'aria-current="page"':''}>我的期待</a><a href="#history" ${page==='history'?'aria-current="page"':''}>心情足迹</a></nav>`;}
function wishesPage(){return `${personalNav()}<section class="page-heading heading-row"><div><h1>存一点期待。</h1><p class="muted">等你想开始的时候，再回来。</p></div><button class="secondary" data-action="add">${icon('plus')} 记下想法</button></section>${data.wishes.length?`<div class="wish-list">${data.wishes.map(w=>`<article class="wish"><div><h2>${esc(w.title)}</h2><p>${esc(w.step||'还没想到第一步也没关系。')}</p></div><div class="wish-actions"><button class="text-button" data-action="start" data-id="${esc(w.id)}">从一小步开始 ${icon('arrow')}</button><button class="icon-button small" data-action="remove-wish" data-id="${esc(w.id)}" aria-label="移除期待：${esc(w.title)}">${icon('trash')}</button></div></article>`).join('')}</div>`:`<div class="empty"><span aria-hidden="true">✳</span><h2>给灵光一现，留个位置。</h2><button class="text-button" data-action="add">记下第一个想法 ${icon('plus')}</button></div>`}`;}
function historyPage(){const groups=new Map();[...data.entries].reverse().forEach(e=>{const key=dayKey(e.at);if(!groups.has(key))groups.set(key,[]);groups.get(key).push(e);});return `${personalNav()}<section class="page-heading"><h1>看看走过的路。</h1><p class="muted">不评分，也不比较。</p></section>${data.entries.length?[...groups.values()].map(entries=>`<section class="timeline-day"><p class="timeline-date">${dateLabel(entries[0].at)}</p><div>${entries.map(e=>`<article class="history-entry"><span class="entry-meta">${new Date(e.at).toLocaleTimeString('zh-CN',{hour:'2-digit',minute:'2-digit'})} · ${e.type==='mood'?'此刻的心情':'一件小事之后'}</span><h2>${esc(e.type==='mood'?(e.mood||'给自己的一句话'):e.title)}</h2>${e.feeling?`<p>${esc(e.feeling)}</p>`:''}${e.note?`<p>${esc(e.note)}</p>`:''}<button class="icon-button small entry-delete" data-action="remove-entry" data-id="${esc(e.id)}" aria-label="删除这条记录">${icon('trash')}</button></article>`).join('')}</div></section>`).join(''):`<div class="empty"><span aria-hidden="true">◌</span><h2>每一种感受，都可以留下来。</h2><button class="text-button" data-action="open-mood">记一笔心情 ${icon('plus')}</button></div>`}`;}
function confirmDialog(title,copy,action,id=''){openDialog(`<h2 id="dialog-title">${title}</h2><p class="muted">${copy}</p><div class="dialog-actions"><button class="secondary" data-action="close">保留</button><button class="text-button danger" data-action="${action}" data-id="${esc(id)}">确认删除</button></div>`);}
function privacyDialog(){openDialog(`<p class="eyebrow">属于你的小空间</p><h2 id="dialog-title">关于你的记录</h2><p class="muted">无需注册。心情、期待和待办只保存在当前浏览器，不会上传到网站服务器。选书问答不保存你的答案。</p><p class="muted">记录不能跨设备同步，清除浏览器数据会丢失。共用设备的人也可能看到这些内容。</p><p class="muted">这里提供自我记录和阅读灵感，不提供心理诊断或治疗。</p><div class="dialog-actions"><button class="secondary" data-action="connect">找一个安心的人聊聊</button><button class="text-button danger" data-action="clear">清空所有记录</button></div>`);}
function connectionDialog(){openDialog(`<p class="eyebrow">不必先整理好情绪</p><h2 id="dialog-title">从一句话开始。</h2><label class="field"><span>改成你自己的语气</span><textarea id="contact-text" maxlength="2000">最近有点想找人聊聊。你这几天有空打个电话，或者一起吃顿饭吗？不用帮我解决什么，陪我说说话就好。</textarea></label><div class="dialog-actions"><button class="primary" data-action="copy-message">复制这段话</button></div><p class="page-note">复制后发给让你安心的人。这里不会替你发送。</p>`);}
function saveAndRender(next,message){if(!save(next))return false;render();if(message)toast(message);return true;}
function focusQuiz(){document.querySelector('#quiz-heading')?.focus({preventScroll:true});animate(app.querySelector('.quiz'));}
document.addEventListener('input',e=>{if(e.target.id==='mood-note')moodDraft=e.target.value;if(e.target.id==='task-input')todoDraft=e.target.value;});
document.addEventListener('change',e=>{if(!e.target.dataset.priority)return;const id=e.target.dataset.priority,priority=e.target.value;const success=saveAndRender({...data,todos:prioritize(data.todos,id,priority)});if(!success){e.target.value=data.todos.find(t=>t.id===id)?.priority||'inbox';}else{[...document.querySelectorAll('[data-priority]')].find(x=>x.dataset.priority===id)?.focus();}});
document.addEventListener('click',async e=>{
 const b=e.target.closest('[data-action]');if(!b)return;
 const action=b.dataset.action,id=b.dataset.id,value=b.dataset.value,book=BOOKS.find(x=>x.id===b.dataset.book);
 if(action==='close')closeDialog();
 if(action==='open-mood')moodDialog();
 if(action==='mood'){selectedMood=selectedMood===value?'':value;dialog.querySelectorAll('.mood').forEach(x=>x.setAttribute('aria-pressed',x.dataset.value===selectedMood));}
 if(action==='shuffle'){nextSuggestion();render();animate(app.querySelector('.idea-copy'));document.querySelector('[data-action="shuffle"]')?.focus();}
 if(action==='literature'){const n=LITERATURE.find(x=>x.id===id);if(n)literatureDialog(n);}
 if(action==='edit-step')startDialog(activeIdea,true);
 if(action==='focus-task')saveAndRender({...data,todos:prioritize(data.todos,id,'now')},'就先做这一件。');
 if(action==='start'){const idea=findIdea(id);if(idea)startDialog(idea);}
 if(action==='reflect')reflectDialog();
 if(action==='feeling'){reflection=value;dialog.querySelectorAll('[data-action="feeling"]').forEach(x=>x.setAttribute('aria-pressed',x.dataset.value===value));}
 if(action==='collect'){if(data.wishes.some(w=>w.sourceId===id)){toast('已经在“我的期待”里了。');return;}const idea=findIdea(id);if(idea)saveAndRender({...data,wishes:[...data.wishes,{...idea,id:uid(),sourceId:id}]},'这份期待，留下来了。');}
 if(action==='add')addDialog();
 if(action==='edit-task'){const t=data.todos.find(x=>x.id===id);if(t)editTaskDialog(t);}
 if(action==='toggle-task'){const task=data.todos.find(t=>t.id===id);if(!task)return;const todos=data.todos.map(t=>t.id===id?{...t,done:!t.done,priority:!t.done?t.priority:(t.priority==='now'?'next':t.priority)}:t);if(!saveAndRender({...data,todos},task.done?'已放回待办。':'这件事，做过了。'))b.checked=task.done;}
 if(action==='move-task'){if(saveAndRender({...data,todos:reorder(data.todos,id,Number(value))},'顺序已调整。')){const task=data.todos.find(t=>t.id===id),group=data.todos.filter(t=>!t.done&&t.priority===task.priority),index=group.findIndex(t=>t.id===id);dialog.querySelectorAll('[data-action="move-task"]').forEach(x=>{x.disabled=Number(x.dataset.value)<0?index===0:index===group.length-1;});}}
 if(action==='remove-task'){const item=data.todos.find(x=>x.id===id),index=data.todos.findIndex(x=>x.id===id);if(item&&saveAndRender({...data,todos:data.todos.filter(x=>x.id!==id)})){closeDialog();undoTask={item,index};toast('已移除这件事。');const undo=document.createElement('button');undo.textContent='撤销';undo.dataset.action='undo-task';document.querySelector('#toast').append(undo);clearTimeout(toast.timer);toast.timer=setTimeout(()=>{document.querySelector('#toast').classList.remove('visible');undoTask=null;},9000);}}
 if(action==='undo-task'&&undoTask){const {item,index}=undoTask;let todos=[...data.todos];if(!todos.some(x=>x.id===item.id)){todos.splice(Math.min(index,todos.length),0,{...item,priority:item.priority==='now'?'next':item.priority});if(item.priority==='now'&&!item.done)todos=prioritize(todos,item.id,'now');if(saveAndRender({...data,todos},'已恢复。'))undoTask=null;}}
 if(action==='confirm-task'&&saveAndRender({...data,todos:data.todos.filter(t=>t.id!==id)},'这件事已删除。'))closeDialog();
 if(action==='concern'){quizConcern=value;quizStyle='';render();focusQuiz();}
 if(action==='reading-style'){quizStyle=value;render();focusQuiz();}
 if(action==='quiz-back'||action==='quiz-reset'){quizConcern='';quizStyle='';render();focusQuiz();}
 if(action==='book'&&book)bookDialog(book);
 if(action==='quote'&&book)bookDialog(book,true,QUOTES[Number(b.dataset.quote)]);
 if(action==='save-book'&&book){if(data.wishes.some(w=>w.bookId===book.id)){toast('这本书已经在“我的期待”里了。');return;}if(save({...data,wishes:[...data.wishes,{id:uid(),bookId:book.id,title:`读一点《${book.title}》`,step:book.start}]})){toast('已放进“我的期待”。');b.disabled=true;b.textContent='已经存下了';}}
 if(action==='privacy')privacyDialog();
 if(action==='connect')connectionDialog();
 if(action==='copy-message'){const field=dialog.querySelector('#contact-text');try{await navigator.clipboard.writeText(field.value);toast('已复制。');}catch{field.focus();field.select();toast('请长按或按 Ctrl+C 复制选中的文字。');}}
 if(action==='remove-wish')confirmDialog('放下这份期待？','不再想做也没关系。移除后无法恢复。','confirm-wish',id);
 if(action==='remove-entry')confirmDialog('删除这条足迹？','删除后无法恢复。','confirm-entry',id);
 if(action==='confirm-wish'&&saveAndRender({...data,wishes:data.wishes.filter(w=>w.id!==id)},'已放下这份期待。'))closeDialog();
 if(action==='confirm-entry'&&saveAndRender({...data,entries:data.entries.filter(x=>x.id!==id)},'这条记录已删除。'))closeDialog();
 if(action==='clear')confirmDialog('清空所有记录？','心情、期待和待办都会被删除，无法恢复。','confirm-clear');
 if(action==='confirm-clear'){try{localStorage.removeItem(KEY);data=emptyData();undoTask=null;storageOK=true;moodDraft='';selectedMood='';todoDraft='';closeDialog();render();toast('记录已清空。');}catch{toast('未能清空，请检查浏览器设置。');}}
});
document.addEventListener('submit',e=>{
 const form=e.target;if(!['mood-form','wish-form','start-form','reflection-form','todo-form','edit-task-form'].includes(form.id))return;e.preventDefault();const fields=new FormData(form);
 if(form.id==='mood-form'){const note=fields.get('note').trim();if(!selectedMood&&!note){toast('选一个心情，或写下几个字就好。');return;}if(save({...data,entries:[...data.entries,{id:uid(),type:'mood',at:new Date().toISOString(),mood:selectedMood,note}]})){selectedMood='';moodDraft='';closeDialog();render();toast('你的感受，记下了。');}}
 if(form.id==='wish-form'){const title=fields.get('title').trim();if(!title){form.elements.title.focus();return;}if(save({...data,wishes:[...data.wishes,{id:uid(),title,step:fields.get('step').trim()}]})){closeDialog();render();toast('已存进“我的期待”。');}}
 if(form.id==='start-form'){const step=fields.get('step').trim();if(!step){form.elements.step.focus();return;}if(data.todos.some(t=>t.id===activeIdea.id)&&!save({...data,todos:data.todos.map(t=>t.id===activeIdea.id?{...t,step}:t)}))return;activeIdea.step=step;render();doingDialog();}
 if(form.id==='reflection-form'){if(!reflection){toast('暂时说不清，也是一种感受。选一个就好。');return;}if(save({...data,entries:[...data.entries,{id:uid(),at:new Date().toISOString(),type:'activity',title:activeIdea.title,step:activeIdea.step,feeling:reflection,note:fields.get('note').trim()}]})){closeDialog();render();toast('这段时间，已经记下了。');}}
 if(form.id==='todo-form'){const title=fields.get('title').trim();if(!title)return;if(save({...data,todos:[...data.todos,{id:uid(),title,step:'',priority:'inbox',done:false}]})){todoDraft='';render();document.querySelector('#task-input').focus();}}
 if(form.id==='edit-task-form'){const title=fields.get('title').trim();if(!title)return;if(save({...data,todos:prioritize(data.todos.map(t=>t.id===form.dataset.id?{...t,title,step:fields.get('step').trim()}:t),form.dataset.id,fields.get('priority')||data.todos.find(t=>t.id===form.dataset.id).priority)})){closeDialog();render();toast('已保存。');}}
});
dialog.addEventListener('click',e=>{if(e.target===dialog){const r=dialog.getBoundingClientRect();if(e.clientX<r.left||e.clientX>r.right||e.clientY<r.top||e.clientY>r.bottom)closeDialog();}});
window.addEventListener('hashchange',()=>{if(dialog.open)closeDialog();render();window.scrollTo({top:0,behavior:'instant'});});
window.addEventListener('storage',e=>{if(e.key===KEY){try{data=e.newValue?normalize(JSON.parse(e.newValue)):emptyData();storageOK=true;render();}catch{storageOK=false;render();}}});
document.addEventListener('visibilitychange',()=>{if(!document.hidden&&page==='today')render();});
render();
