import {createClock,remainingMs,startClock,pauseClock,restoreClock,displayTime} from './pause-clock.js';
const esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const enc=encodeURIComponent;
const clockKey='manmanlai.pause.v1';
// Incrementing requestId makes late results from an older search or location request harmless.
let clock=createClock(),rerender=()=>{},query='',schools=[],support=null,locationMessage='',locationBusy=false,searchBusy=false,requestId=0;
try{clock=restoreClock(JSON.parse(sessionStorage.getItem(clockKey)));}catch{}
function persistClock(){try{sessionStorage.setItem(clockKey,JSON.stringify(clock));}catch{}}
const LETTERS=[
 ['换了环境，就不再闪闪发光了吗？','刚到一个优秀的人很多的地方，我也会不自觉地拿自己和别人比。以前做得不错的事，到了这里好像突然不算什么了。那种失落是真实的，不用急着说服自己别在意。','可我慢慢发现，身边多了很多很厉害的人，并不意味着我原来的努力、好奇和善意就不见了。我可以欣赏别人，也可以继续喜欢那个还在摸索的自己。','今天如果愿意，记下一件你做起来真正在意的事。先不管它能不能让别人看见。'],
 ['Club、rush、面试，不是人生的总成绩','社团招新、rush、面试，一轮接着一轮的时候，我也会觉得，自己好像总在等一个被选中的结果。看到别人有了新去处，心里着急，很正常。','但一次没通过，不等于我这个人不够好。比起赶上每一场活动，我更想问问自己：我喜欢和什么样的人待在一起？什么事会让我愿意花时间？答案不一定在最热闹的地方。','下次准备报名之前，可以先停一停：我是想去看看，还是只是怕自己落在后面？'],
 ['人生很长，不用在这个学期证明一切','来到新地方以后，连很普通的小事都要重新学。听懂一堂课、办好一张卡、认识一个能说话的人，已经会花掉不少力气。','所以我不想再把每个学期都过成一次证明。适应有自己的速度；有些日子只是把饭吃好、把觉睡够，也是在照顾生活。慢一点，并不等于停在原地。','这周先选一件小事就好。做到了，就让它算数。'],
 ['有很多朋友，也仍然可以觉得孤单','和朋友一起上课、吃饭，回到房间时却还是觉得空落落的。我想，这两种感受可以同时存在。孤单不代表朋友不够好，也不代表自己哪里出了问题。','有时候我们需要的不是更多热闹，而是有人能听见一句真实的“我最近不太好”。如果一时不知道和谁说，学校的咨询师也可以是一个开始；不必等到事情变得很严重。','可以先给一个让你安心的人发条消息。不用想好整段话，说一句近况就够了。'],
 ['难过以后，也可以慢慢走回来','一段关系有了距离时，我还是会难过，也会忍不住想：是不是自己做错了什么。后来我才慢慢学着把这两件事分开：有人离开，是一件会让人伤心的事；但这不等于我的价值也跟着少了。','我理解的平静，不是从此不需要别人，也不是遇到失去时一点都不疼。只是心乱的时候，先照顾好今天：吃顿饭，出门走走，和信任的人说几句话。需要更多支持时，也可以去找学校的咨询师。','我依然想认真珍惜身边的人。同时也想相信，生活有了空缺，我能一点点重新安放它。不必立刻变得坚强；难过之后，仍然可以慢慢走回来。']
];
export function lettersPage(){return `<section class="page-heading"><p class="eyebrow">来自一位留学生的经历 · 与你分享</p><h1>慢慢来，真的没关系。</h1><p class="muted">环境变了，你的价值没有变少。</p></section><div class="student-letter"><p>这个小空间，起于刚到异国、进入大学时的孤单，也起于一次次被朋友理解、主动走进学校心理咨询室的经历。做这个项目，让我重新有了一件想投入的事。我希望你来到这里时，也能感到：不用着急，你不是一个人。</p><p class="page-note">根据发起人的真实经历整理</p></div><div class="letter-list">${LETTERS.map(([title,...paragraphs],i)=>`<details class="letter-${i}"><summary>${title}</summary>${paragraphs.map(p=>`<p>${p}</p>`).join('')}</details>`).join('')}</div><div class="support-actions"><a class="secondary" href="#pause">先歇一会</a><a class="text-button" href="#campus">了解学校的支持 ↗</a><button class="text-button" data-action="connect">找一个安心的人聊聊</button></div>`;}
export function pausePage(){const finished=clock.status==='finished',running=clock.status==='running';return `<section class="pause-space"><a class="pause-back" href="#today">← 回到今天</a><p class="eyebrow">这几分钟，不需要证明什么</p><h1>${finished?'慢慢回来就好。':'先把自己，放回此刻。'}</h1><p class="pause-hint">${finished?'准备好时，再继续你的一天。':'自然呼吸。走神了，也可以轻轻回来。'}</p><div class="pause-orb ${running?'is-breathing':''}"><span class="pause-ripple pause-ripple-inner" aria-hidden="true"></span><span class="pause-ripple pause-ripple-outer" aria-hidden="true"></span><span id="pause-time" role="timer" aria-label="剩余时间" aria-live="off">${displayTime(remainingMs(clock))}</span><span id="pause-state">${finished?'这段时间，留给了自己':running?'正在静坐':clock.status==='paused'?'已暂停':'选一段属于自己的时间'}</span></div><div class="pause-durations" role="group" aria-label="静坐时长">${[180,300,600].map(s=>`<button data-space="duration" data-seconds="${s}" aria-pressed="${clock.duration===s}" ${running?'disabled':''}>${s/60} 分钟</button>`).join('')}</div><div class="pause-controls"><button class="primary" data-space="${running?'pause':'start'}">${running?'暂停':finished?'再坐一会':clock.status==='paused'?'继续':'开始静坐'}</button>${clock.status!=='idle'?'<button class="text-button" data-space="reset">结束这次</button>':''}</div><p id="pause-announcement" class="sr-only" role="status">${finished?'静坐计时结束。准备好时，再继续你的一天。':''}</p><details class="pause-guide"><summary>第一次尝试？</summary><p>找一个坐得舒服的位置，眼睛可以睁着。留意自然的呼吸，或者脚与地面接触的感觉，不必控制节奏，也不用清空脑海。如果不舒服，随时停下，看看周围。</p><p>离开此页会暂停；刷新会恢复本标签页的计时。锁屏或切到后台时，结束提示可能延后，回到页面会校准剩余时间。</p><a class="source-external" href="https://www.nhs.uk/every-mind-matters/mental-wellbeing-tips/how-to-meditate-for-beginners/" target="_blank" rel="noopener noreferrer">练习参考 · NHS 冥想入门 ↗</a></details></section>`;}
async function campusApi(path){const response=await fetch(path);const data=await response.json();if(!response.ok)throw new Error(data.error||'查询暂时不可用。');return data;}
function schoolMarkup(c){return `<button class="campus-school" data-space="school" data-school="${esc(c.id)}"><span class="campus-school-name">${esc(c.name)}</span><span class="campus-school-place">${esc([c.city,c.country].filter(Boolean).join(' · '))}</span><span aria-hidden="true">→</span></button>`;}
function supportMarkup(data){const c=data.school;return `<section class="campus-detail"><p class="eyebrow">已选学校 · 请确认校区</p><h2>${esc(c.name)}</h2><p class="muted">${esc([c.city,c.country].filter(Boolean).join(' · '))}</p>${data.resources.length?`<p class="campus-detail-intro">在学校官网找到这些心理支持页面：</p>${data.resources.map(r=>`<article class="campus-resource"><a href="${esc(r.url)}" target="_blank" rel="noopener noreferrer">${esc(r.title)} ↗</a>${r.address?`<address>${esc(r.address)}</address>`:''}<p class="page-note">${r.source==='curated'?`资料核对：${esc(r.checked)}。`:'来自学校官网。'}预约、费用、校区和开放时间以官网为准。</p></article>`).join('')}`:`<p class="campus-detail-intro">暂时没有找到可核实的校内心理支持页面。你可以访问学校官网，或继续搜索官网内容。</p>`}<div class="support-actions"><a class="text-button" href="${esc(c.website)}" target="_blank" rel="noopener noreferrer">学校主页 ↗</a><a class="text-button" href="https://www.google.com/search?q=${enc(`site:${c.domain} student mental health counseling`)}" target="_blank" rel="noopener noreferrer">搜索学校官网 ↗</a></div><p class="page-note">学校信息来自 ROR 机构目录；官网页面查找日期：${esc(data.checked)}。自动查找可能遗漏资料，请以学校公告为准。</p></section>`;}
export function campusPage(){return `<section class="page-heading"><p class="eyebrow">把求助的第一步，变得近一点</p><h1>学校里，也有人愿意听。</h1><p class="muted">输入学校名称，或允许定位后先找到附近的学校，再查看它的官方支持页面。</p></section><form id="campus-form"><label class="field" for="campus-query"><span>你的学校</span></label><div class="campus-search"><input id="campus-query" name="school" value="${esc(query)}" maxlength="120" required placeholder="如 NYU、University of Toronto" autocomplete="organization"><button class="primary" type="submit" ${searchBusy?'disabled':''}>${searchBusy?'查找中…':'查找学校'}</button></div></form><div class="campus-location"><span>或者</span><button class="text-button locate-button" data-space="locate" ${locationBusy?'disabled':''}>${locationBusy?'正在查找…':'用当前位置找附近学校 →'}</button></div><p class="page-note location-note">仅点击定位后才请求权限。坐标由设备直接发送给 BigDataCloud 换算城市；本站只接收城市与国家，不保存位置。定位无法判断你就读哪所学校，请在结果中确认。</p><p id="campus-status" role="status">${esc(locationMessage)}</p><div id="campus-results">${schools.length?`<section class="campus-schools"><p class="eyebrow">选择你的学校</p>${schools.map(schoolMarkup).join('')}</section>`:''}${support?supportMarkup(support):''}</div><p class="page-note">学校机构信息来自 <a href="https://ror.org/" target="_blank" rel="noopener noreferrer">ROR ↗</a>。搜索结果不是紧急援助；如有即时危险，请联系当地紧急服务。</p>`;}
export function afterSpaceRender(page,render){rerender=render;document.body.classList.toggle('in-pause',page==='pause');if(page!=='pause'&&clock.status==='running'){clock=pauseClock(clock);persistClock();}if(page==='pause'){document.title=clock.status==='finished'?'静坐结束 · 慢慢来':'歇一会 · 慢慢来';tick();}else document.title='慢慢来 · 你不是一个人';}
function tick(){if(clock.status==='running'&&remainingMs(clock)<=0){clock={...clock,remaining:0,endAt:null,status:'finished'};persistClock();if(location.hash==='#pause'){rerender();document.title='静坐结束 · 慢慢来';}return;}const el=document.querySelector('#pause-time');if(el)el.textContent=displayTime(remainingMs(clock));}
setInterval(tick,250);document.addEventListener('visibilitychange',()=>{if(!document.hidden)tick();});
document.addEventListener('input',e=>{if(e.target.id==='campus-query')query=e.target.value;});
document.addEventListener('submit',async e=>{if(e.target.id!=='campus-form')return;e.preventDefault();query=e.target.elements.school.value.trim();if(query.length<2)return;const current=++requestId;searchBusy=true;locationBusy=false;schools=[];support=null;locationMessage='正在查找学校…';rerender();try{const data=await campusApi(`/api/campus/search?q=${enc(query)}`);if(current!==requestId)return;schools=data.schools;locationMessage=schools.length?`找到 ${schools.length} 所可能匹配的学校，请确认校名与校区。`:'没有找到匹配的学校。可以试试学校的英文全称。';}catch(error){if(current!==requestId)return;locationMessage=error.message;}finally{if(current===requestId){searchBusy=false;if(location.hash==='#campus')rerender();}}});
document.addEventListener('click',e=>{const b=e.target.closest('[data-space]');if(!b)return;const a=b.dataset.space;
 if(a==='duration'&&clock.status!=='running'){clock=createClock(Number(b.dataset.seconds));persistClock();rerender();document.querySelector('[data-space="pause"], [data-space="start"]')?.focus({preventScroll:true});}
 if(a==='start'){clock=startClock(clock);persistClock();rerender();document.querySelector('[data-space="pause"], [data-space="start"]')?.focus({preventScroll:true});}
 if(a==='pause'){clock=pauseClock(clock);persistClock();rerender();document.querySelector('[data-space="pause"], [data-space="start"]')?.focus({preventScroll:true});}
 if(a==='reset'){clock=createClock(clock.duration);persistClock();rerender();document.querySelector('[data-space="pause"], [data-space="start"]')?.focus({preventScroll:true});}
 if(a==='school'){const id=b.dataset.school;const current=++requestId;support=null;locationMessage='正在查找这所学校的支持页面…';rerender();campusApi(`/api/campus/support?id=${enc(id)}`).then(data=>{if(current!==requestId)return;support=data;schools=[];locationMessage=data.resources.length?`找到 ${data.resources.length} 个学校官网支持页面。`:'已找到学校，但没有找到可核实的心理支持页面。';if(location.hash==='#campus'){rerender();document.querySelector('.campus-detail')?.scrollIntoView({block:'start',behavior:'smooth'});}}).catch(error=>{if(current!==requestId)return;locationMessage=error.message;if(location.hash==='#campus')rerender();});}
 if(a==='locate'){if(locationBusy)return;if(!navigator.geolocation||!window.isSecureContext){locationMessage='当前浏览器无法定位，请输入学校名称。';rerender();return;}locationBusy=true;searchBusy=false;schools=[];support=null;locationMessage='请在浏览器提示中选择是否允许定位。';const current=++requestId;rerender();navigator.geolocation.getCurrentPosition(async pos=>{if(current!==requestId)return;try{const url=`https://api.bigdatacloud.net/data/reverse-geocode-client?latitude=${pos.coords.latitude}&longitude=${pos.coords.longitude}&localityLanguage=en`;const response=await fetch(url);if(!response.ok)throw new Error('位置服务暂时不可用。');const place=await response.json();const city=place.city||place.locality;const country=place.countryCode;if(!city||!country)throw new Error('无法识别当前城市。');const data=await campusApi(`/api/campus/nearby?city=${enc(city)}&country=${enc(country)}`);if(current!==requestId)return;schools=data.schools;locationMessage=schools.length?`找到 ${city} 的 ${schools.length} 所候选学校，请选择你就读的学校。`:`目录中暂未找到 ${city} 的学校。请手动输入校名。`;}catch(error){if(current!==requestId)return;locationMessage=`${error.message} 你仍可手动输入校名。`;}finally{if(current===requestId){locationBusy=false;if(location.hash==='#campus')rerender();}}},error=>{if(current!==requestId)return;locationBusy=false;locationMessage=error.code===1?'未获得定位权限。输入学校名称，也可以继续查找。':error.code===3?'定位超时，请重试或输入学校名称。':'暂时无法获取位置，请输入学校名称。';if(location.hash==='#campus')rerender();},{enableHighAccuracy:false,timeout:12000,maximumAge:300000});}
});
