import {CAMPUSES,matchCampuses,nearbyCampuses} from './campus-data.js';
import {createClock,remainingMs,startClock,pauseClock,restoreClock,displayTime} from './pause-clock.js';
const esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const enc=encodeURIComponent;
const clockKey='manmanlai.pause.v1';
let clock=createClock(),rerender=()=>{},query='',results=[],resultMode='',locationMessage='',locationBusy=false,point=null,requestId=0;
try{clock=restoreClock(JSON.parse(sessionStorage.getItem(clockKey)));}catch{}
function persistClock(){try{sessionStorage.setItem(clockKey,JSON.stringify(clock));}catch{}}
const LETTERS=[
 ['换了环境，就不再闪闪发光了吗？','以前很容易被看见，来到一所优秀的人很多的大学，却突然觉得自己普通了。这样的落差，可以被认真对待。','你看到的人变多了，你曾经的努力、好奇心和善意却没有消失。你不需要在每一个房间里都最耀眼，才值得喜欢自己。','今天先写下一件你在意、而不是为了超过别人而做的事。'],
 ['Club、rush、面试，不是人生的总成绩。','社团招新、business fraternity 的 rush、朋友不断更新的履历，很容易让一段校园生活变成一场场筛选。紧张并不全是你“不够自信”，环境也在不断传递比较的信号。','一份拒信、一次没聊好的 networking，都无法概括你。你可以挑真正感兴趣的活动，也可以留出不参加任何活动的晚上。归属感不只存在于某个组织的名单上。','给下一场活动问一句：我是真的好奇，还是只是怕落后？'],
 ['人生很长，不用在这个学期证明一切。','“人生是一场马拉松”对我们来说，是允许调整步速、休息和换方向。它不必变成另一场要求你坚持到底的比赛。','刚到异国，你还在适应语言、生活和关系。慢一点认识校园，慢一点找到朋友，都是生活的一部分。','把这周的期待缩小一点：吃好一顿饭，和一个安心的人聊聊，做一件自己想做的小事。'],
 ['有很多朋友，也仍然可以觉得孤单。','有人一起上课、聚会，不一定就有人知道你清晨醒来时的失落。你可以感谢已有的朋友，同时承认自己还想要更深一点的连接。','不用等到情绪整理得很漂亮才开口。找一个让你安心的朋友、家人，或者学校的咨询师，说一句“我最近不太好，想让你陪我聊聊”。','不要求对方马上解决问题，只邀请一次真诚的交流。']
];
export function lettersPage(){return `<section class="page-heading"><p class="eyebrow">来自一位留学生的经历 · 与你分享</p><h1>慢慢来，真的没关系。</h1><p class="muted">环境变了，你的价值没有变少。</p></section><div class="student-letter"><p>这个小空间，起于刚到异国、进入大学时的孤单，也起于一次次被朋友理解、主动走进学校心理咨询室的经历。做这个项目，让我重新有了一件想投入的事。我希望你来到这里时，也能感到：不用着急，你不是一个人。</p><p class="page-note">根据发起人的真实经历整理</p></div><div class="letter-list">${LETTERS.map(([title,...paragraphs],i)=>`<details class="letter-${i}"><summary>${title}</summary>${paragraphs.map(p=>`<p>${p}</p>`).join('')}</details>`).join('')}</div><div class="support-actions"><a class="secondary" href="#pause">先歇一会</a><a class="text-button" href="#campus">了解学校的支持 ↗</a><button class="text-button" data-action="connect">找一个安心的人聊聊</button></div>`;}
export function pausePage(){const finished=clock.status==='finished',running=clock.status==='running';return `<section class="pause-space"><a class="pause-back" href="#today">← 回到今天</a><p class="eyebrow">这几分钟，不需要证明什么</p><h1>${finished?'慢慢回来就好。':'先把自己，放回此刻。'}</h1><p class="pause-hint">${finished?'准备好时，再继续你的一天。':'自然呼吸。走神了，也可以轻轻回来。'}</p><div class="pause-orb"><span id="pause-time" role="timer" aria-label="剩余时间" aria-live="off">${displayTime(remainingMs(clock))}</span><span id="pause-state">${finished?'这段时间，留给了自己':running?'正在静坐':clock.status==='paused'?'已暂停':'选一段属于自己的时间'}</span></div><div class="pause-durations" role="group" aria-label="静坐时长">${[180,300,600].map(s=>`<button data-space="duration" data-seconds="${s}" aria-pressed="${clock.duration===s}" ${running?'disabled':''}>${s/60} 分钟</button>`).join('')}</div><div class="pause-controls"><button class="primary" data-space="${running?'pause':'start'}">${running?'暂停':finished?'再坐一会':clock.status==='paused'?'继续':'开始静坐'}</button>${clock.status!=='idle'?'<button class="text-button" data-space="reset">结束这次</button>':''}</div><p id="pause-announcement" class="sr-only" role="status">${finished?'静坐计时结束。准备好时，再继续你的一天。':''}</p><details class="pause-guide"><summary>第一次尝试？</summary><p>找一个坐得舒服的位置，眼睛可以睁着。留意自然的呼吸，或者脚与地面接触的感觉，不必控制节奏，也不用清空脑海。如果不舒服，随时停下，看看周围。</p><p>离开此页会暂停；刷新会恢复本标签页的计时。锁屏或切到后台时，结束提示可能延后，回到页面会校准剩余时间。</p><a class="source-external" href="https://www.nhs.uk/every-mind-matters/mental-wellbeing-tips/how-to-meditate-for-beginners/" target="_blank" rel="noopener noreferrer">练习参考 · NHS 冥想入门 ↗</a></details></section>`;}
function resourceMarkup(c){return `<article class="campus-result"><p class="eyebrow">${Number.isFinite(c.distance)?`距校区参考点约 ${Math.round(c.distance)} 公里 · 请确认学校`:'学校官网资料'}</p><h2>${esc(c.name)}</h2><p class="campus-english">${esc(c.english)}</p><p>${esc(c.center)}</p><address>${esc(c.address)}</address><div class="support-actions"><a class="secondary" href="${c.url}" target="_blank" rel="noopener noreferrer">学校官网 ↗</a><a class="text-button" href="https://www.google.com/maps/search/?api=1&query=${enc(c.address)}" target="_blank" rel="noopener noreferrer">地址地图 ↗</a>${c.addressSource?`<a class="text-button" href="${c.addressSource}" target="_blank" rel="noopener noreferrer">地址出处 ↗</a>`:''}</div><p class="page-note">核对日期：2026-09-22。预约、费用、适用校区及开放时间请以官网为准。</p></article>`;}
function searchLinks(q){return `<div class="external-search"><p>${results.length?'也可以继续查找：':'暂未收录这所学校。可以带着校名继续搜索：'}</p><div class="support-actions"><a class="secondary" href="https://www.google.com/search?q=${enc(q+' university counseling psychological services official website')}" target="_blank" rel="noopener noreferrer">搜索学校官网 ↗</a><a class="text-button" href="https://www.google.com/maps/search/?api=1&query=${enc(q+' university counseling center')}" target="_blank" rel="noopener noreferrer">搜索中心地址 ↗</a></div><p class="page-note">外部搜索结果尚未核实；请确认是学校官方页面，避免把广告当作校内服务。</p></div>`;}
export function campusPage(){return `<section class="page-heading"><p class="eyebrow">把求助的第一步，变得近一点</p><h1>学校里，也有人愿意听。</h1><p class="muted">输入校名，或定位查找附近已收录的学校。</p></section><form id="campus-form"><label class="field" for="campus-query"><span>学校名称或城市</span></label><div class="campus-search"><input id="campus-query" name="school" value="${esc(query)}" maxlength="120" required placeholder="如 NYU、南加州大学、Ann Arbor" autocomplete="off"><button class="primary" type="submit">查找</button></div></form><button class="text-button locate-button" data-space="locate" ${locationBusy?'disabled':''}>${locationBusy?'正在获取位置…':'用当前位置查找'}</button><p class="page-note location-note">定位只在本机匹配，不保存、不上传。打开地图搜索时，位置才会交给 Google Maps。不能定位也可以输入校名。</p><p id="campus-status" role="status">${esc(locationMessage)}</p><div id="campus-results">${results.map(resourceMarkup).join('')}${resultMode==='search'?searchLinks(query):''}${resultMode==='location'&&!results.length?`<div class="external-search"><p>附近暂无已核实的学校资料。你可以输入学校名称，或打开地图继续找。</p><a class="secondary" href="https://www.google.com/maps/search/?api=1&query=${enc('university counseling center near '+point.lat.toFixed(2)+','+point.lon.toFixed(2))}" target="_blank" rel="noopener noreferrer">用大致位置搜索地图 ↗</a><p class="page-note">这是外部地图搜索，不是已核实的校内中心名单。</p></div>`:''}</div><details class="coverage"><summary>已收录哪些学校？</summary><p>目前核实了 ${CAMPUSES.length} 所学校；定位只匹配这份名单中约 50 公里内的校区，并不代表你就读的学校。</p><div class="campus-picks">${CAMPUSES.map(c=>`<button data-space="school" data-school="${c.id}">${c.name}</button>`).join('')}</div></details>`;}
export function afterSpaceRender(page,render){rerender=render;document.body.classList.toggle('in-pause',page==='pause');if(page!=='pause'&&clock.status==='running'){clock=pauseClock(clock);persistClock();}if(page==='pause'){document.title=clock.status==='finished'?'静坐结束 · 慢慢来':'歇一会 · 慢慢来';tick();}else document.title='慢慢来 · 你不是一个人';}
function tick(){if(clock.status==='running'&&remainingMs(clock)<=0){clock={...clock,remaining:0,endAt:null,status:'finished'};persistClock();if(location.hash==='#pause'){rerender();document.title='静坐结束 · 慢慢来';}return;}const el=document.querySelector('#pause-time');if(el)el.textContent=displayTime(remainingMs(clock));}
setInterval(tick,250);document.addEventListener('visibilitychange',()=>{if(!document.hidden)tick();});
document.addEventListener('input',e=>{if(e.target.id==='campus-query')query=e.target.value;});
document.addEventListener('submit',e=>{if(e.target.id!=='campus-form')return;e.preventDefault();query=e.target.elements.school.value.trim();if(!query)return;requestId++;locationBusy=false;results=matchCampuses(query);resultMode='search';locationMessage=results.length?`找到 ${results.length} 所已收录学校。`:'没有匹配的已收录学校。';rerender();const status=document.querySelector('#campus-status');if(status){status.tabIndex=-1;status.focus({preventScroll:true});status.scrollIntoView({block:'nearest'});}});
document.addEventListener('click',e=>{const b=e.target.closest('[data-space]');if(!b)return;const a=b.dataset.space;
 if(a==='duration'&&clock.status!=='running'){clock=createClock(Number(b.dataset.seconds));persistClock();rerender();document.querySelector('[data-space="pause"], [data-space="start"]')?.focus({preventScroll:true});}
 if(a==='start'){clock=startClock(clock);persistClock();rerender();document.querySelector('[data-space="pause"], [data-space="start"]')?.focus({preventScroll:true});}
 if(a==='pause'){clock=pauseClock(clock);persistClock();rerender();document.querySelector('[data-space="pause"], [data-space="start"]')?.focus({preventScroll:true});}
 if(a==='reset'){clock=createClock(clock.duration);persistClock();rerender();document.querySelector('[data-space="pause"], [data-space="start"]')?.focus({preventScroll:true});}
 if(a==='school'){requestId++;locationBusy=false;const c=CAMPUSES.find(x=>x.id===b.dataset.school);query=c.name;results=[c];resultMode='search';locationMessage='已找到学校资料。';rerender();}
 if(a==='locate'){if(locationBusy)return;if(!navigator.geolocation||!window.isSecureContext){locationMessage='当前浏览器无法定位，请输入学校名称。';rerender();return;}locationBusy=true;locationMessage='请在浏览器提示中选择是否允许定位。';const current=++requestId;rerender();navigator.geolocation.getCurrentPosition(pos=>{if(current!==requestId)return;point={lat:pos.coords.latitude,lon:pos.coords.longitude};results=nearbyCampuses(point);resultMode='location';locationBusy=false;locationMessage=results.length?`找到 ${results.length} 所附近已收录学校，请确认校名与校区。`:'定位成功，附近尚无已收录学校。';if(location.hash==='#campus')rerender();},error=>{if(current!==requestId)return;locationBusy=false;locationMessage=error.code===1?'未获得定位权限。输入学校名称，也可以继续查找。':error.code===3?'定位超时，请重试或输入学校名称。':'暂时无法获取位置，请输入学校名称。';if(location.hash==='#campus')rerender();},{enableHighAccuracy:false,timeout:12000,maximumAge:300000});}
});
